export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as Explore } from './Explore'
export { default as Uikit } from './Uikit'
export { default as NotFound } from './NotFound'
